

### DELETE A PERSON
DELETE http://localhost:3001/api/persons/2

### ADD A NEW PERSON
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "id": 6,
    "name": "Carlos Vedder",
    "number": "555-555-5555"
}



