### GET ALL
GET http://localhost:3001/api/blogs


### POST A NEW BLOG
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY2NGJmYzg2ODVmYzRiNjNhOGM5OWRkNyIsImlhdCI6MTcxNjMzNzQyOCwiZXhwIjoxNzE2NDIzODI4fQ._4X4v5WCxYgM-UthzsayVmhFuW9MjOgObvEvcAKpZ9Q

{
    "author": "Root New 5",
    "title": "JWT",
    "url": "https://jwt.io",
    "likes": 18,
    "userId": "664bfc8685fc4b63a8c99dd7"
}


### DELETE A BLOG
DELETE http://localhost:3001/api/blogs/664d45965ad57c56f12fed0a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY2NGJmYzg2ODVmYzRiNjNhOGM5OWRkNyIsImlhdCI6MTcxNjM0MDMzMSwiZXhwIjoxNzE2NDI2NzMxfQ.KuCKgmV-3cCUGcsLrZEamXWDcoIiuhEF5WVAoILZyf0


### CHANGE A BLOG
PUT http://localhost:3001/api/blogs/6646906be1f3e3afe2758889
Content-Type: application/json

{
    "author": "Root",
    "title": "Express",
    "url": "https://expressjs.com/",
    "likes": 500,
    "userid": "664934037e8f752a040e822f"
}


### CREATE A USER
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "root",
    "name": "Root",
    "password": "1988"
}