### GET ALL
GET http://localhost:3001/api/blogs


### POST A NEW BLOG
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvZHJpZ28iLCJpZCI6IjY2NDkxMjQ4YTE1MDQ1YWU4Nzg3YmVlZCIsImlhdCI6MTcxNjI0NTA2MSwiZXhwIjoxNzE2MzMxNDYxfQ.u-Grwxt7-Ex9hUOZn0A8ZphPKpgxjhHDN7tZnk7TkrY

{
    "author": "Root",
    "title": "JWT",
    "url": "https://jwt.io",
    "likes": 18,
    "userId": "66491248a15045ae8787beed"
}


### DELETE A BLOG
DELETE http://localhost:3001/api/blogs/664bd342aca87c3a989b7581
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvZHJpZ28iLCJpZCI6IjY2NDkxMjQ4YTE1MDQ1YWU4Nzg3YmVlZCIsImlhdCI6MTcxNjI0NTA2MSwiZXhwIjoxNzE2MzMxNDYxfQ.u-Grwxt7-Ex9hUOZn0A8ZphPKpgxjhHDN7tZnk7TkrY


### CHANGE A BLOG
PUT http://localhost:3001/api/blogs/6646906be1f3e3afe2758889
Content-Type: application/json

{
    "author": "Root",
    "title": "Express",
    "url": "https://expressjs.com/",
    "likes": 500,
    "userid": "664934037e8f752a040e822f"
}


### CREATE A USER
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "rodri",
    "name": "Rodrigo",
    "password": "1988"
}