### POST
POST http://localhost:3001/persons
Content-Type: application/json

{
    "id": 5,
    "name": "Eddie Vedder",
    "number": "040-123456"
}

### DELETE A PERSON
DELETE http://localhost:3001/persons/6


